In [12]:
import pandas as pd 
from sklearn.model_selection import train_test_split
%config Completer.use_jedi = False
from lfs import keyword_free, keyword_gift, keyword_whynot, LFs
from snorkel.labeling import PandasLFApplier, filter_unlabeled_dataframe
from snorkel.labeling.model import MajorityLabelVoter, LabelModel
import numpy as np
# importing the module
import timeit
import random
import glob
all_filenames = [i for i in glob.glob('data/*.csv')]

df = pd.concat([pd.read_csv(f) for f in all_filenames ])
df = df.rename(columns={"CLASS": "label", "CONTENT": "text"})
# df["label"].replace({"Quality": HAM, "Spam": SPAM}, inplace=True)

In [13]:
# df = df[:100]

In [14]:
# applier = PandasLFApplier(lfs=[keyword_free, keyword_gift, keyword_whynot])
applier = PandasLFApplier(lfs = LFs)

In [15]:
def frm_scratch(repeat=10,df=None):
    for i in range(repeat):
        print(i)
#         rlist = random.sample(range(20), 5)
        rlist = [0,1,2,3,4]
        lf_used = [LFs[x] for x in rlist]
        applier = PandasLFApplier(lfs = lf_used)
        model = MajorityLabelVoter(cardinality=2)
        soi_labels = applier.apply(df=df, progress_bar=False)
        print(soi_labels)
#         probs_test= model.predict_proba(L=soi_labels)
# #         print(probs_test)
#         df_test_filtered, probs_test_filtered = filter_unlabeled_dataframe(
#             X=df, y=probs_test, L=soi_labels
#         )
#         df_test_filtered = df_test_filtered.reset_index(drop=True)
#         print(df_test_filtered)
#         print(probs_test_filtered)
#         print(df.shape)
#         print(df_test_filtered.shape)
        print(model.predict(L=soi_labels))

In [16]:
def use_cache(repeat=100, df=None, vectors=None):
    for i in range(repeat):
        print(i)
#         rlist = random.sample(range(20), 5)
        rlist = [0,1,2,3,4]
        lf_used = [LFs[x] for x in rlist]
        used_vecs = []
        for f in lf_used:
            used_vecs.append(vectors[f])
        model = MajorityLabelVoter(cardinality=2)
        soi_labels = np.array(used_vecs).transpose()
        print(soi_labels)
        probs_test= model.predict_proba(L=soi_labels)
#         print(probs_test)
        df_test_filtered, probs_test_filtered = filter_unlabeled_dataframe(
            X=df, y=probs_test, L=soi_labels
        )
#         print(probs_test_filtered)
#         print(df.shape)
#         print(df_test_filtered.shape)
        df_test_filtered = df_test_filtered.reset_index(drop=True)
        print(model.predict(L=soi_labels))

In [17]:
applier = PandasLFApplier(lfs = LFs)
func_labels = applier.apply(df=df, progress_bar=False)
cached_vectors = dict(zip(LFs, np.transpose(func_labels)))

In [18]:
LFs

[func: textblob_polarity,
 func: textblob_subjectivity,
 func: regex_link,
 func: has_person_nlp,
 func: pos_vbprps_stuff,
 func: check,
 func: keyword_my,
 func: keyword_subscribe,
 func: keyword_please,
 func: keyword_song,
 func: keyword_shakira,
 func: keyword_google,
 func: keyword_money,
 func: keyword_facebook,
 func: keyword_twitter,
 func: keyword_free,
 func: keyword_gift,
 func: keyword_why not,
 func: nothttp,
 func: short_comment]

In [19]:
cached_vectors

{func: textblob_polarity: array([-1, -1, -1, ..., -1, -1,  0]),
 func: textblob_subjectivity: array([0, 0, 0, ..., 0, 0, 0]),
 func: regex_link: array([-1, -1, -1, ..., -1, -1, -1]),
 func: has_person_nlp: array([-1, -1, -1, ..., -1,  0, -1]),
 func: pos_vbprps_stuff: array([-1, -1, -1, ..., -1, -1, -1]),
 func: check: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_my: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_subscribe: array([-1, -1, -1, ...,  1, -1, -1]),
 func: keyword_please: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_song: array([ 0,  0,  0, ..., -1, -1, -1]),
 func: keyword_shakira: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_google: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_money: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_facebook: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_twitter: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_free: array([-1, -1, -1, ..., -1, -1, -1]),
 func: keyword_gift: array([-1, -

In [20]:
start1 = timeit.default_timer()

frm_scratch(repeat=10,df=df)

end1 = timeit.default_timer()

print(end1-start1)

0
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
1
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
2
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
3
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
4
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
5
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
6
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
7
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 

In [21]:
start2 = timeit.default_timer()

use_cache(repeat=10, df=df, vectors=cached_vectors)

end2 = timeit.default_timer()

print(end2-start2)

0
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
1
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
2
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
3
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
4
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
5
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
6
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 [-1  0 -1 -1 -1]
 [-1  0 -1  0 -1]
 [ 0  0 -1 -1 -1]]
[0 0 0 ... 0 0 0]
7
[[-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 [-1  0 -1 -1 -1]
 ...
 

In [24]:
LFs[0]==LFs[0]

True

In [25]:
f=LFs[0]

In [26]:
f

func: textblob_polarity

In [31]:
x = [mf for mf in LFs if (mf in LFs[:5] and mf != f)]

In [32]:
x

[func: textblob_subjectivity,
 func: regex_link,
 func: has_person_nlp,
 func: pos_vbprps_stuff]

In [29]:
LFs

[func: textblob_polarity,
 func: textblob_subjectivity,
 func: regex_link,
 func: has_person_nlp,
 func: pos_vbprps_stuff,
 func: check,
 func: keyword_my,
 func: keyword_subscribe,
 func: keyword_please,
 func: keyword_song,
 func: keyword_shakira,
 func: keyword_google,
 func: keyword_money,
 func: keyword_facebook,
 func: keyword_twitter,
 func: keyword_free,
 func: keyword_gift,
 func: keyword_why not,
 func: nothttp,
 func: short_comment]